apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chouette.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
        {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chouette
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "9001"
        prometheus.io/scrape: "true"
        scheduler.alpha.kubernetes.io/affinity: |
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  { "matchExpressions":
                    [ {"key": "track", "operator": "NotIn", "values": ["build"] } ]
                  }
                ]
              }
            }
          }
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - command:
            - /cloud_sql_proxy
            - -instances={{ .Values.gcpDatabaseInstance}}
            - -credential_file=/etc/chouette-service-account/credentials.json
            - -log_debug_stdout
          image: gcr.io/cloudsql-docker/gce-proxy:1.15
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 28
          name: chouette-sql-proxy
          resources:
            requests:
              cpu: 50m
              memory: 40Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/chouette-service-account
              name: chouette-service-account
        - env:
            - name: JAVA_OPTS
              value: -server -Xms2048m -Xmx{{ .Values.resources.xmx }} -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true
                -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dconfig.location=/etc/application-config/application.properties
                -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/jboss/data/
            - name: LANG
              value: en_US.UTF-8
            - name: TZ
              value: Europe/Oslo
            - name: CHOUETTE_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: chouette-db-username
                  name: ror-chouette-secret
            - name: CHOUETTE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: chouette-db-password
                  name: ror-chouette-secret
            - name: CHOUETTE_IEV_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: chouette-iev-db-username
                  name: ror-chouette-secret
            - name: CHOUETTE_IEV_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: chouette-iev-db-password
                  name: ror-chouette-secret
            - name: IEV_REFERENTIAL_ADMIN_INITIAL_ENCRYPTED_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: chouette-admin-initial-encrypted-password
                  name: ror-chouette-secret
            - name: IEV_REFERENTIAL_USER_INITIAL_ENCRYPTED_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: chouette-user-initial-encrypted-password
                  name: ror-chouette-secret
          image: {{ .Values.image.identifier }}
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - /opt/jboss/wildfly/bin/jboss-cli.sh -c --command=:shutdown
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: chouette_iev/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          name: chouette
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 5005
              name: debug
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: chouette_iev/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memLimit }}
            requests:
              cpu: {{ .Values.resources.cpuRequest }}
              memory: {{ .Values.resources.memRequest }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/chouette-service-account
              name: chouette-service-account
            - mountPath: /opt/jboss/wildfly/standalone/configuration/standalone.xml
              name: chouette-config
              subPath: standalone.xml
            - mountPath: /etc/application-config/application.properties
              name: chouette-config
              readOnly: true
              subPath: application.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: chouette-service-account
      terminationGracePeriodSeconds: 60
      volumes:
        - name: chouette-service-account
          secret:
            defaultMode: 420
            secretName: ror-chouette-sa-key
        - configMap:
            defaultMode: 420
            name: chouette-config
          name: chouette-config